### PR TITLE
Add CLIENT LIST command and fix CLIENT INFO

### LINKED ISSUE #1910: Add support for redis command: CLIENT LIST

### PR DESCRIPTION
**Pull request by K4ST0R**
### Description

Fix #1910

I have added the implementation of the following command to the project [CLIENT LIST](https://redis.io/commands/client-list).

This PR also fix an issue with CLIENT INFO : new fields were added in new redis version, the regex was not extracting the good values.

---

### Checklist

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by leibale** [comment]
@K4ST0R Thanks for contributing (and not for the first time!) :)

Looks like it's not working with 5.0 and 6.0, you can test it locally using
```
npm run test -w ./packages/client -- --redis-version 5.0
npm run test -w ./packages/client -- --redis-version 6.0
```

**Comment by leibale** [comment]
@K4ST0R We have to make sure that the "supported versions" (5 - current) work as expected.. (sometimes it's not that fun or easy, but it has to be done..)

**Comment by K4ST0R** [comment]
Yes I totally understand! Everything is fine now, normally :)

**Comment by leibale** [comment]
@K4ST0R sorry for the huge delay... Review my changes? :pray:

**Comment by K4ST0R** [comment]
@leibale Don't worry! LGTM! :) Thanks to you.

**Pull request merged**
