### PR TITLE
Add support for `FT.SEARCH NOCONTENT`

### PR DESCRIPTION
**Pull request by brettburch**
### Description
This PR implements the TODO item at 
 
https://github.com/redis/node-redis/blob/294cbf8367295ac81cbe51ce2932493ab80493f1/packages/search/lib/commands/SEARCH.ts#L9

Similar to [#2488
](https://github.com/redis/node-redis/pull/2488)

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by leibale** [comment]
@brettburch thanks for contributing! but... if I remember correctly the `NOCONTENT` option changes the reply structure, which will break `transformReply`. You can use `RETURN: []` to achieve (almost) the same thing..

In order to support the `NOCONTENT` option it should be added as a separated command (see [AGGREGATE_WITHCURSOR](https://github.com/redis/node-redis/blob/master/packages/search/lib/commands/AGGREGATE_WITHCURSOR.ts) for example).

**Comment by brettburch** [comment]
>  if I remember correctly the `NOCONTENT` option changes the reply structure, which will break `transformReply`. You can use `RETURN: []` to achieve (almost) the same thing..

Ahh, yes, that's true. Only the keys are returned with this option. To your point, for my initial research on this I did:
```
import {
  SearchRawReply,
  transformArguments,
  transformReply as transformSearchReply,
} from '@redis/search/dist/commands/SEARCH';

...

  async search(
    ...
    options?: SearchOptions,
    additionalParams?: { NOCONTENT?: true },
  ): Promise<SearchReply> {
    const allArgs = transformArguments(index, query, options);
    if (additionalParams) {
      if (additionalParams.NOCONTENT) {
        allArgs.push('NOCONTENT');
      }
    }

    const rawReply = await this.redisClient.sendCommand<SearchRawReply>(allArgs);
    return transformSearchReply(rawReply, additionalParams?.NOCONTENT || false);
  }
```
In this case the documents that are returned have id set but no value.

> The `NOCONTENT` option should be added as a "special command" (see [AGGREGATE_WITHCURSOR](https://github.com/redis/node-redis/blob/master/packages/search/lib/commands/AGGREGATE_WITHCURSOR.ts) for example).

Sounds good. I will move towards a `SEARCH_WITHNOCONTENT` implementation.

Thanks for the review!

**Comment by leibale** [comment]
@brettburch name it `SEARCH_NOCONTENT/searchNoContent`, not `SEARCH_WITHNOCONTENT`
Thanks again! :)

**Comment by leibale** [comment]
@brettburch see the edit, sorry about the confusion...

**Comment by brettburch** [comment]
@leibale I believe I understood your feedback, but let me know if there's anything else to update here.

**Comment by brettburch** [comment]
@leibale I see the node 14 test runs are failing. Is node 14 still supported? Only 18 and 20 are currently active/maintained. If 14 is supported in this package I can investigate the test failures.

**Comment by leibale** [comment]
@brettburch I just did not remove them from the tests matrix yet.. I'll take care of it this week.

I think this PR is ready.. :)

**Comment by leibale** [comment]
@brettburch `redis@4.6.9`/`@redis/search@1.1.4` is on npm :tada:

**Comment by brettburch** [comment]
Great, thanks for the update @leibale ! 🎉

**Pull request merged**
