### PR TITLE
Set FIRST_KEY_INDEX if a script accepts keys

### PR DESCRIPTION
**Pull request by poiuj**
### Description

Setting FIRST_KEY_INDEX ensures we send the script to the right node, instead of sending to random node and repeating on getting MOVED response. Relying on a random node send increases traffic and exceeds maxCommandRedirections configuration with non-zero probability.

### Checklist

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by poiuj** [comment]
@leibale do you have specific concerns about this change?

**Comment by leibale** [comment]
1. sorry about the long delay
2. IIRC, NUMBER_OF_KEYS is used by the cluster client to extract the key, I don't think FIRST_KEY_INEDX is needed
3. this API does not exist anymore, we are using https://github.com/redis/node-redis/blob/master/packages/client/lib/client/parser.ts instead

**Comment by poiuj** [comment]
> IIRC, NUMBER_OF_KEYS is used by the cluster client to extract the key, I don't think FIRST_KEY_INEDX is needed
That's not what I observed, that's why I propose the change. But maybe it has changed since then.

> sorry about the long delay
IIRC, NUMBER_OF_KEYS is used by the cluster client to extract the key, I don't think FIRST_KEY_INEDX is needed
this API does not exist anymore, we are using https://github.com/redis/node-redis/blob/master/packages/client/lib/client/parser.ts instead
Not sure I understand. Do you mean we no longer use `defineScript`? This PR is not relevant anymore?

**Comment by leibale** [comment]
Transform arguments uses the `BasicCommandParser` class instead of an array, and instead of using "FIRST_KEY_INDEX", we use `pushKey`.

There are a few reasons for this change:
1. in some commands they first key position is dynamic
2. for client-side caching we need to know all the keys, not just the first one

**Comment by poiuj** [comment]
It makes sense. I updated the branch and verified that the issue is gone with the new approach.

**Pull request closed without merging**
