### PR TITLE
HSCAN NOVALUES support (v5)

### PR DESCRIPTION
**Pull request by sjpotter**
### Description

> Describe your pull request here

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Review by leibale — CHANGES_REQUESTED** [review]
add support for `RedisClient/RedisCluster/RedisSentinel`.`hScanValuesIterator` too please

**Comment by leibale** [comment]
duplicate of #2711

**Comment by sjpotter** [comment]
added iterator support on RedisClient type, don't see any iterator on any of the other clients, should we add them all there as well?

**Comment by leibale** [comment]
@sjpotter this should be implemented as part of #2657

**Pull request merged**
