### PR TITLE
DOC-4195: add TCEs to the range query page

### PR DESCRIPTION
**Pull request by dwdougherty**
### Description

Tabbed code examples (TCEs) for the exact match query page. Please merge as soon as possible.

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by sjpotter** [comment]
@dwdougherty is it a problem that the test is failing?

**Comment by dwdougherty** [comment]
How is it failing? I runs successfully on my system.

**Comment by sjpotter** [comment]
github test "doctests" in the github actions ."all checks have failed"

**Comment by sjpotter** [comment]
so I comitted the first one, but still failing as query_em.json doesn't exist?

**Comment by sjpotter** [comment]
ok, merged in the initial pr into all of these PRs, helps me make progress.

**Comment by sjpotter** [comment]
@leibale looks fine to me, is there anything I'm not understanding that would be an issue?

**Pull request closed without merging**
