### PR TITLE
Export SetOptions type in redis/client command

### PR DESCRIPTION
**Pull request by dqtkien**
### Description
#2243 

> Describe your pull request here

---

### Checklist

- [x] Does `npm test` pass with this change (including linting)?
- [x] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by leibale** [comment]
@dqtkien thanks for this PR! you should've exported it in `client/index.ts`, not `packages/client/lib/cluster/commands.ts`
https://github.com/redis/node-redis/blob/master/packages/client/index.ts

**Comment by dqtkien** [comment]
@leibale tks for your time, pls take a look with my PR.

**Comment by dqtkien** [comment]
@leibale tks for your time, pls take a look with my PR.

**Review by leibale — APPROVED** [review]

**Comment by leibale** [comment]
@dqtkien tnx! :)

**Pull request merged**
