### PR TITLE
Add support for `CLIENT NO-TOUCH`

### PR DESCRIPTION
**Pull request by codrin-ch**
### Description

> Describe your pull request here

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

Fix for https://github.com/redis/node-redis/issues/2455

### CODE REVIEW

**Comment by leibale** [comment]
@codrin-ch thanks for contributing! We are actively working on v5, which changes the way commands are defined a bit (see [`PING` in the v5 branch](https://github.com/redis/node-redis/blob/v5/packages/client/lib/commands/PING.ts) from example). If you can convert this PR to be for v5 it'll be awesome :)

**Comment by codrin-ch** [comment]
@leibale if there is no urgency for 7.2 new functionalities support maybe it would be better to avoid combining migration to v5 with new functionalities and prepare a separate branch for 7.2 support with all the requirements and release it afterward v5 reaches master and the version is validated and stable?

**Comment by leibale** [comment]
@codrin-ch the 7.2 commands are in the v5 backlog anyway.. :)

**Comment by leibale** [comment]
@codrin-ch `redis@4.6.9`/`@redis/client@1.5.10` is on npm :tada:

**Pull request merged**
