### PR TITLE
disconnect in basic example

### PR DESCRIPTION
**Pull request by reviewher**
### Description

The basic example just hangs.  It was missing the disconnect.

---

### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by leibale** [comment]
I'm pretty sure that most of the node apps are REST APIs, and in that scenario you don't want to `.disconnect()`/`.quit()`

@simonprickett @guyroyse WDUT?

**Comment by reviewher** [comment]
It's a "basic example" and listed as the first example in the README.  There are no instructions for how to run it.

"Obviously" you start a local server and copy-paste the example to a MJS file and run it with node.  Try it.  The process will just hang.

The documentation can include a note about when disconnect/quit are appropriate.

**Comment by leibale** [comment]
Maybe we should leave the example as is and add a note with a link to [this section](https://github.com/redis/node-redis#disconnecting)

**Comment by reviewher** [comment]
If it is the case that "most of the node apps are REST APIs", then the "basic example" should be a simple REST server using raw Node HTTP server or ExpressJS.

The idea of a "basic example" IMHO is something you can run.  A person who is new to `node-redis` will see the snippet with an actual import statement etc. and just test it out, wondering why the process is stuck.

**Comment by simonprickett** [comment]
I like the idea of having it in there?

**Review by taylorsweetman — APPROVED** [review]

**Pull request merged**
